POST https://localhost:3000/users
Content-Type: application/json
 
{ 
    "username": "ceejay",
    "nome": "Candido",
    "email": "ceejay@gmail.com",
    "password": "teste"
}
 
###
 
POST https://localhost:3000/users/login
Content-Type: application/json
 
{
    "username": "evandro",
    "password": "november6ix!"
}

### 
GET https://localhost:3000/users

###
 
GET https://localhost:3000/users/nome/m

###
PUT https://localhost:3000/users/1
Content-Type: application/json 
 
{
    "editor": "true"
}

###

DELETE https://localhost:3000/users/1

###
DELETE https://localhost:3000/users/11

### 
//----------------------------------------------------------------

//generos requests
POST https://localhost:3000/generos
Content-Type: application/json
 
{
    "nome": "R&B"
}

###
GET https://localhost:3000/generos

###
GET https://localhost:3000/generos/1

###
GET https://localhost:3000/generos/nome/jazz

###
PUT https://localhost:3000/generos/1
Content-Type: application/json 
 
{
    "nome": "R&B"
}

###
DELETE https://localhost:3000/generos/1

###
//----------------------------------------------------------------

//Artista requests
POST https://localhost:3000/artistas
Content-Type: application/json
 
{
    "nome": "6lack"
}

###
GET https://localhost:3000/artistas

###
DELETE https://localhost:3000/artistas/6

###
GET https://localhost:3000/artistas/nome/B

###
PUT https://localhost:3000/artistas/7
Content-Type: application/json 
 
{
    "nome": "Bruno King"
}

###
DELETE https://localhost:3000/generos/1

###
//----------------------------------------------------------------

//Album requests
POST https://localhost:3000/albuns
Content-Type: application/json
 
{
    "nome": "Art & History",
    "artistaId": 1
}

### 
GET https://localhost:3000/albuns

### 
GET https://localhost:3000/albuns/1

###
GET https://localhost:3000/albuns/nome/d

###
PUT https://localhost:3000/albuns/1
Content-Type: application/json 
 
{
    "imageId": 1
}

###
DELETE https://localhost:3000/albuns/1

###
//----------------------------------------------------------------

// Musics requests
POST https://localhost:3000/musics
Content-Type: multipart/form-data
 
{
    "userId": 1,
    "titulo": "Puro",
    "generoId": 1,
    "artistaId": 1,
    "url": 
}

### 
GET https://localhost:3000/musics/genero/rap

### 
GET https://localhost:3000/musics/1

###
GET https://localhost:3000/musics/title/d

###
PUT https://localhost:3000/musics/1
Content-Type: application/json 
 
{
    "nome": "Desconhecido"
}

###
DELETE https://localhost:3000/musics/1

###
GET https://localhost:3000/upload/image/Maria/1716421408168-alhilal-logo

###
GET https://localhost:3000/images
###
GET https://localhost:3000/images/user/1

###
DELETE https://localhost:3000/videos/1

###
GET https://localhost:3000/upload/image/:username/:filename
###
GET https://localhost:3000/download/silva/images/1717109105289-ANNA_JOYCE_755x470.jpg
###
// Criticas
POST https://localhost:3000/criticas/album
Content-Type: application/json 
 
{
    "comentario": "GOAT!",
    "userId": 3,
    "albumId": 3,
    "pontuacao": 5
}

###
GET https://localhost:3000/criticas/album
###
PUT https://localhost:3000/criticas/album/2
Content-Type: application/json 
 
{
    "comentario": "esperava mais da mother!",
    "pontuacao": 3
}
###
DELETE https://localhost:3000/criticas/album/3
###
DELETE https://localhost:3000/criticas/user/1

###
// PlayList Testes
//Criar
POST https://localhost:3000/playlists
Content-Type: application/json

{
    "nome": "Classic",
    "userId": 1
}

###
// Adicionar musica
POST https://localhost:3000/playlists/1/musics
Content-Type: application/json

{
    "playlistId": 1,
    "musicId": 1
}

###
// Listar musicas da playlist
GET https://localhost:3000/playlists/1/musics

###
// limpar playlist
DELETE https://localhost:3000/playlists/1/musics

###
// eliminar playlist
DELETE https://localhost:3000/playlists/1

###
// partilha de ficheiros
POST https://localhost:3000/share
Content-Type: application/json

{
    "mediaType": "music",
    "mediaId": 1,
    "userDest": 2,
    "userOwner": 1
}

###
GET https://localhost:3000/shared/musics/2

###
//Grupos
POST https://localhost:3000/grupo
Content-Type: application/json

{
    "userOwner": 1,
    "nomeGrupo": "Al Hilal"
}
###
GET https://localhost:3000/grupo/1

###
POST https://localhost:3000/grupo/1/2

###
POST https://localhost:3000/grupo/pedido/1/3

###
PUT https://localhost:3000/grupo/1/3

###
DELETE https://localhost:3000/grupo/1

###
PUT https://localhost:3000/grupo/1/2/owner